# Generated by Django 5.0.4 on 2026-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rename_academics_co_code_idx_academics_c_code_21c5c3_idx_and_more'),
        ('accounts', '0003_alter_customuser_managers_and_more'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollment__student_35bb4d_idx',
            old_name='enrollment_stu_ca_idx',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course_assignment'), name='unique_student_enrollment'),
        ),
    ]
