# Generated by Django 5.0.4 on 2026-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_courseassignment'),
        ('accounts', '0002_profiles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='academics_c_code_21c5c3_idx',
            old_name='academics_co_code_idx',
        ),
        migrations.RenameIndex(
            model_name='courseassignment',
            new_name='academics_c_semeste_c81b32_idx',
            old_name='academics_ca_sem_year_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='academics_d_code_791f98_idx',
            old_name='academics_de_code_idx',
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('course', 'semester', 'year'), name='unique_course_assignment'),
        ),
    ]
