# Generated by Django 5.0.4 on 2026-03-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__enrollm_9957ca_idx',
            old_name='attendance_enr_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendance__date_61f2e1_idx',
            old_name='attendance_date_idx',
        ),
    ]
